Resources:
  AppNode:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-4fc58420
      KeyName: aws-keypair
      SecurityGroups:
        - !Ref AppNodeSG
      Tags:
        - Key: Name
          Value: Testing
      UserData: !Base64 |
        #!/bin/bash 
        yum update -y
        yum install httpd -y
        service httpd start
        cd /var/www/html/
        echo " Testing Clodformation" > index.html
        chkconfig httpd on
  AppNodeSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: WebServer
      GroupDescription: For instance allow ssh and http ports
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0  